Release Candidate v3.5
Enhancements to decompress scripts, blacklists.t and minor bug fixes.

diff --git a/blacklist/decompress b/blacklist/decompress
--- a/blacklist/decompress
+++ b/blacklist/decompress
@@ -10,6 +10,31 @@ alias show='_vyatta_op_run show'
 alias run='/opt/vyatta/bin/vyatta-op-cmd-wrapper'
 alias check='/bin/cli-shell-api'
 
+atexit () {
+	tput cnorm
+}
+trap atexit exit ${?}
+
+DMASQ_MSG="
+cache-size 2048
+listen-on eth0 # LAN Interface
+listen-on eth2 # LAN Interface
+listen-on lo
+name-server 208.67.220.220
+name-server 208.67.222.222
+name-server 2620:0:ccc::2
+name-server 2620:0:ccd::2
+options bogus-priv
+options domain=ubnt.home # Set to match your chosen home domain
+options except-interface=eth1 # Don't listen on the WAN Interface
+options expand-hosts
+options listen-address=127.0.0.1
+options localise-queries
+options strict-order
+system
+
+"
+
 install_menu () {
 	local IFS=' '
 	local PS3='Enter option number and hit return => '
@@ -23,9 +48,22 @@ do
 	select CHOICE in ${OPTIONS[@]}; do
 		case ${REPLY} in
 			1)		clear console
+					check existsActive service dns forwarding
+					if [[ $? == 0 ]]
+					then
 					./setup
 					./blacklist.t
 					break
+					else
+						tput setaf 1
+						echo 'CANNOT PROCEED: [service dns forwarding] must be configured first!'
+						tput setaf 7
+						echo 'Sample dns forwarding (dnsmasq) configuration:'
+						tput setaf 3
+						echo -ne ${DMASQ_MSG}
+						tput setaf 7
+					fi
+					return 1
 					;;
 			2)		clear console
 					if /opt/vyatta/bin/yesno -n 'Do you want to completely remove Blacklist? [y/N]: '
@@ -42,10 +80,16 @@ do
 					if [[ $? == 0 ]]
 					then
 						RESULT=$(run show configuration commands | grep blacklist > /config/user-data/blacklist.cmds)
-						echo -ne "\ndnsmasq blacklist configuration backed up to /config/user-data/blacklist.cmds.\n\nTo restore, run:\n\tconfigure\n\tsource /config/user-data/blacklist.cmds\n\tcommit\n\tsave\n\texit\n\n" | fold -s -w ${COLUMNS}
+						tput setaf 2
+						echo -ne "\ndnsmasq blacklist configuration backed up to /config/user-data/blacklist.cmds.\n\n"
+						tput setaf 7
+						echo -ne "To restore, run:\n\tconfigure\n\tsource /config/user-data/blacklist.cmds\n\tcommit\n\tsave\n\texit\n\n" | fold -s -w ${COLUMNS}
 					else
+						tput setaf 1
 						echo -ne "\ndnsmasq blacklist isn't configured, nothing to backup!\n\n"
+						tput setaf 7
 					fi
+					break
 					;;
 			5|*)	return 0
 					;;
@@ -58,7 +102,7 @@ CDIR="$(pwd)"
 
 # Make sure script runs as root
 if [[ ${EUID} -eq 0 ]]; then
-	echo 'This script must be run as the admin user, not root!'
+	echo 'This script must be run as the ubnt admin user, not root!'
 	exit 1
 fi
 
