4.0.alpha.102715 NOT YET USABLE!
Mainly working, major rewrite of key functions. Now using hashrefs for
code compaction and reuse. Added functionality will conditional DNS
forwarding for listed domains, as well as blackholing of wildcard
domains. dnsmasq blackhole fqdns are first checked against any
blackhole domain lists and rejected if there is already an existing
domain.

diff --git a/AdBlock/payload/installer b/AdBlock/payload/installer
--- a/AdBlock/payload/installer
+++ b/AdBlock/payload/installer
@@ -6,7 +6,7 @@
 #
 # This program is distributed in the hope that it will be useful, but
 # WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the GNU
 # General Public License for more details.
 #
 # A copy of the GNU General Public License is available as
@@ -20,16 +20,17 @@
 # Date: September 2015
 #
 # **** End License ****
-# Install dnsmasq ADBLOCK and blacklist blocking onto an EdgeMax router
+# Install dnsmasq BLACKLIST and blacklist blocking onto an EdgeMax router
 # Use at your own risk
 #
+set -o errtrace
 
-VERSION="v2.2"
+VERSION="v2.4"
 
 # Uncomment for debugging or syntax checking
 # set -x
 # Syntax check - uncomment for non execution dry run:
-# set -n
+# set -nv
 
 # Make sure script runs as root
 if [[ ${EUID} != 0 ]]
@@ -44,23 +45,21 @@ OPRUN=/opt/vyatta/bin/vyatta-op-cmd-wrapper
 CFGRUN=/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper
 API=/bin/cli-shell-api
 shopt -s expand_aliases
-
-alias begin='${CFGRUN} begin'
-alias commit='${CFGRUN} commit'
-alias copy='${CFGRUN} copy'
-alias delete='${CFGRUN} delete'
-alias discard='${CFGRUN} discard'
-alias end='${CFGRUN} end'
-alias save='${CFGRUN} save'
-alias set='${CFGRUN} set'
-alias version='${OPRUN} show version'
+alias begin="${CFGRUN} begin"
+alias commit="${CFGRUN} commit"
+alias copy="${CFGRUN} copy"
+alias delete="${CFGRUN} delete"
+alias discard="${CFGRUN} discard"
+alias end="${CFGRUN} end"
+alias save="${CFGRUN} save"
+alias set="${CFGRUN} set"
+alias version="${OPRUN} show version"
 
 SHOWVER=$(version | sed 's/$/;/g')
 BUILD=$(echo ${SHOWVER} | awk 'BEGIN {RS=";"} /Build ID:/ {print $3}')
 VER=$(echo ${SHOWVER} | awk 'BEGIN {RS=";"} /Version:/ {print $2}')
 ME="${0##*/} ${VERSION}: "
 ERROR=0
-
 
 # Check version and set up environment
 is_version ()
@@ -71,7 +70,7 @@ is_version ()
 	# v1.6.0: build 4716006
 	# v1.7.0: build 4783374
 
-	if [[ ${BUILD} > 4716006 ]]   # Script is only supported on OS v1.6.0 & above
+	if [[ ${BUILD} > 4716006 ]]	  # Script is only supported on OS v1.6.0 & above
 	then
 		return 0
 	else
@@ -79,106 +78,155 @@ is_version ()
 	fi
 }
 
-
 # Make sure we clean up session on deliberate and accidental exits
 atexit ()
 {
+	trap "" ERR
 	end
+	trap - ERR
+}
+trap atexit exit ${?}
+
+# Enable error tracing functionality
+##########################################################################
+# Copyright (c): Hilario J. Montoliu <hmontoliu@gmail.com>
+# This program is free software; you can redistribute it and/or modify it
+# under the terms of the GNU General Public License as published by the
+# Free Software Foundation; either version 2 of the License, or (at your
+# option) any later version.  See http://www.gnu.org/copyleft/gpl.html for
+# the full text of the license.
+##########################################################################
+report_error ()
+{
+	trap "" ERR
+	local ERR=$1 # error status
+	local LINE=$2 # LINENO
+	local FUNCTLINE=$3
+	local CMD="$4"
+	local STACK="$5"
+	echo "==================================================="
+	echo "Error: '${CMD}' exited with status: ${ERR} at line ${LINE}"
+
+	if [ "${STACK}" != "::" ]; then
+		echo -n "	... Error at ${STACK} "
+		[ -z ${FUNCTLINE:=0} ] && echo -n "called at line ${FUNCTLINE}"
+	else
+		echo -n "	... internal debug info from function ${FUNCNAME} (line ${FUNCTLINE})"
+	fi
+	echo
+	echo "==================================================="
+	trap - ERR
 }
 
-# Install adblock and bogon support
-install_adblock_support ()
+trap 'report_error $? ${LINENO} ${BASH_LINENO} "${BASH_COMMAND}" $(printf "::%s" ${FUNCNAME[@]})'  ERR
+# End of error tracing functions
+##################################################################
+
+# Install blacklist support
+install_blacklist_support ()
 {
-	SCRIPTS="/config/scripts"
-	ADBLOCK="update-blacklists-dnsmasq.pl"
-	CFGDIR="/opt/vyatta/share/vyatta-cfg/templates"
-	WWWDIR="/config/wizard/feature/ADBlock"
-	GUI="GUI"
-	ERROR=0
+	CONFIG="/config/scripts"
+	BLACKLIST="update-blacklists-dnsmasq.pl"
+	TEMPLATES="/opt/vyatta/share/vyatta-cfg/templates/service/dns"
+#	WWWDIR="/config/wizard/feature/ADBlock"
+#	GUI="GUI"
 
-	if [[ ! -d "${SCRIPTS}" ]]
+	if [[ ! -d "${CONFIG}" ]]
 	then
-		install -d -o root -g root -m 0755 "${SCRIPTS}/" || ERROR=1
+		install -d -o root -g root -m 0755 "${CONFIG}/"
 	fi
 
-	echo "Installing ${ADBLOCK} to ${SCRIPTS}/"
-	install -o root -g root -m 0755 "${ADBLOCK}" "${SCRIPTS}/${ADBLOCK}" || ERROR=1
+	echo "Installing ${BLACKLIST} to ${CONFIG}/"
+	install -o root -g root -m 0755 "${BLACKLIST}" "${CONFIG}/${BLACKLIST}" || ERROR=1
 
-	if [[ ! -d "${WWWDIR}/" ]]
-	then
-		install -d -o www-data -g users -m 0755 "${WWWDIR}/" || ERROR=1
-	fi
+#	if [[ ! -d "${WWWDIR}/" ]]
+#	then
+#		install -d -o www-data -g users -m 0755 "${WWWDIR}/" || ERROR=1
+#	fi
 
-# 	for i in "${GUI}/"*
-# 	do
-# 		install -o www-data -g users -m 0755 ${i} "${WWWDIR}/"$(basename ${i}) || ERROR=1
-# 	done
+#	for i in "${GUI}/"*
+#	do
+#		install -o www-data -g users -m 0755 ${i} "${WWWDIR}/"$(basename ${i}) || ERROR=1
+#	done
 
-	echo "Installing blacklist configuration templates for ${ADBLOCK}..."
-	cp -rf service/ "${CFGDIR}/"
+	echo "Installing blacklist configuration templates for ${BLACKLIST}..."
+	cp -rf forwarding/ "${TEMPLATES}/"
 
 	echo "Opening EdgeMax configuration session..."
-	begin || ERROR=1
+	begin
 
-	echo "Creating starter blacklists and task scheduler entry for ${ADBLOCK}..."
-	set service dns forwarding blacklist enabled true  || ERROR=1
-	set service dns forwarding blacklist blackhole 0.0.0.0 || ERROR=1
-	set service dns forwarding blacklist exclude msdn.com || ERROR=1
-	set service dns forwarding blacklist exclude appleglobal.112.2o7.net || ERROR=1
-	set service dns forwarding blacklist exclude cdn.visiblemeasures.com || ERROR=1
-	set service dns forwarding blacklist exclude hb.disney.go.com || ERROR=1
-	set service dns forwarding blacklist exclude googleadservices.com || ERROR=1
-	set service dns forwarding blacklist exclude hulu.com || ERROR=1
-	set service dns forwarding blacklist exclude static.chartbeat.com || ERROR=1
-	set service dns forwarding blacklist exclude survey.112.2o7.net || ERROR=1
-	set service dns forwarding blacklist include beap.gemini.yahoo.com || ERROR=1
-	set service dns forwarding blacklist source openphish.com description 'OpenPhish automatic phishing detection'
-	set service dns forwarding blacklist source openphish.com prefix 'htt.*//'
-	set service dns forwarding blacklist source openphish.com url 'https://openphish.com/feed.txt'
-	set service dns forwarding blacklist source someonewhocares.org description 'Zero based host and domain list' || ERROR=1
-	set service dns forwarding blacklist source someonewhocares.org prefix '0.0.0.0' || ERROR=1
-	set service dns forwarding blacklist source someonewhocares.org url 'http://someonewhocares.org/hosts/zero/' || ERROR=1
-	set service dns forwarding blacklist source winhelp2002.mvps.org description 'Zero based host and domain list' || ERROR=1
-	set service dns forwarding blacklist source winhelp2002.mvps.org prefix '0.0.0.0' || ERROR=1
-	set service dns forwarding blacklist source winhelp2002.mvps.org url 'http://winhelp2002.mvps.org/hosts.txt' || ERROR=1
-	set service dns forwarding blacklist source malwaredomainlist.com description '127.0.0.1 based host and domain list' || ERROR=1
-	set service dns forwarding blacklist source malwaredomainlist.com prefix '127.0.0.1' || ERROR=1
-	set service dns forwarding blacklist source malwaredomainlist.com url 'http://www.malwaredomainlist.com/hostslist/hosts.txt' || ERROR=1
-	set service dns forwarding blacklist source yoyo.org description 'Fully Qualified Domain Names only - no prefix to strip' || ERROR=1
-	set service dns forwarding blacklist source yoyo.org prefix '' || ERROR=1
-	set service dns forwarding blacklist source yoyo.org url 'http://pgl.yoyo.org/as/serverlist.php?hostformat=nohtml&showintro=1&mimetype=plaintext' || ERROR=1
-	set service dns forwarding blacklist source zeustracker.abuse.ch/compromised description 'abuse.ch ZeuS compromised URL blacklist' || ERROR=1
-	set service dns forwarding blacklist source zeustracker.abuse.ch/compromised prefix '' || ERROR=1
-	set service dns forwarding blacklist source zeustracker.abuse.ch/compromised url 'https://zeustracker.abuse.ch/blocklist.php?download=compromised' || ERROR=1
-	set service dns forwarding blacklist source zeustracker.abuse.ch/hostfile description 'abuse.ch ZeuS blocklist host file' || ERROR=1
-	set service dns forwarding blacklist source zeustracker.abuse.ch/hostfile prefix '127.0.0.1' || ERROR=1
-	set service dns forwarding blacklist source zeustracker.abuse.ch/hostfile url 'https://zeustracker.abuse.ch/blocklist.php?download=hostfile' || ERROR=1
-	set system task-scheduler task update_blacklists executable path /config/scripts/update-blacklists-dnsmasq.pl || ERROR=1
-	set system task-scheduler task update_blacklists interval 6h || ERROR=1
+	echo "Creating starter blacklists and task scheduler for ${BLACKLIST}..."
+	set service dns forwarding blacklist blackhole 0.0.0.0
+	set service dns forwarding blacklist disabled false
+	set service dns forwarding blacklist hosts exclude appleglobal.112.2o7.net
+	set service dns forwarding blacklist hosts exclude cdn.visiblemeasures.com
+	set service dns forwarding blacklist hosts exclude googleadservices.com
+	set service dns forwarding blacklist hosts exclude hb.disney.go.com
+	set service dns forwarding blacklist hosts exclude hulu.com
+	set service dns forwarding blacklist hosts exclude msdn.com
+	set service dns forwarding blacklist hosts exclude static.chartbeat.com
+	set service dns forwarding blacklist hosts exclude survey.112.2o7.net
+	set service dns forwarding blacklist hosts include beap.gemini.yahoo.com
+	set service dns forwarding blacklist hosts source hpHosts description 'hpHosts optimized in hosts format'
+	set service dns forwarding blacklist hosts source hpHosts prefix 127.0.0.1
+	set service dns forwarding blacklist hosts source hpHosts url 'http://hosts-file.net/download/HOSTS-Optimized.txt'
+	set service dns forwarding blacklist hosts source openphish.com description 'OpenPhish automatic phishing detection'
+	set service dns forwarding blacklist hosts source openphish.com prefix 'htt.*//'
+	set service dns forwarding blacklist hosts source openphish.com url 'https://openphish.com/feed.txt'
+	set service dns forwarding blacklist hosts source someonewhocares.org description 'Zero based host and domain list'
+	set service dns forwarding blacklist hosts source someonewhocares.org prefix 0.0.0.0
+	set service dns forwarding blacklist hosts source someonewhocares.org url 'http://someonewhocares.org/hosts/zero/'
+	set service dns forwarding blacklist hosts source volkerschatz.com description 'Ad server blacklists'
+	set service dns forwarding blacklist hosts source volkerschatz.com prefix 'htt.*/'
+	set service dns forwarding blacklist hosts source volkerschatz.com url 'http://www.volkerschatz.com/net/adpaths'
+	set service dns forwarding blacklist hosts source winhelp2002.mvps.org description 'Zero based host and domain list'
+	set service dns forwarding blacklist hosts source winhelp2002.mvps.org prefix 0.0.0.0
+	set service dns forwarding blacklist hosts source winhelp2002.mvps.org url 'http://winhelp2002.mvps.org/hosts.txt'
+	set service dns forwarding blacklist hosts source www.malwaredomainlist.com description '127.0.0.1 based host and domain list'
+	set service dns forwarding blacklist hosts source www.malwaredomainlist.com prefix 127.0.0.1
+	set service dns forwarding blacklist hosts source www.malwaredomainlist.com url 'http://www.malwaredomainlist.com/hostslist/hosts.txt'
+	set service dns forwarding blacklist hosts source yoyo.org description 'Fully Qualified Domain Names only - no prefix to strip'
+	set service dns forwarding blacklist hosts source yoyo.org prefix ''
+	set service dns forwarding blacklist hosts source yoyo.org url 'http://pgl.yoyo.org/as/serverlist.php?hostformat=nohtml&showintro=1&mimetype=plaintext'
+	set service dns forwarding blacklist hosts source zeustracker.abuse.ch/compromised description 'abuse.ch ZeuS compromised URL blacklist'
+	set service dns forwarding blacklist hosts source zeustracker.abuse.ch/compromised prefix ''
+	set service dns forwarding blacklist hosts source zeustracker.abuse.ch/compromised url 'https://zeustracker.abuse.ch/blocklist.php?download=compromised'
+	set service dns forwarding blacklist hosts source zeustracker.abuse.ch/hostfile description 'abuse.ch ZeuS blocklist host file'
+	set service dns forwarding blacklist hosts source zeustracker.abuse.ch/hostfile prefix 127.0.0.1
+	set service dns forwarding blacklist hosts source zeustracker.abuse.ch/hostfile url 'https://zeustracker.abuse.ch/blocklist.php?download=hostfile'
+	set service dns forwarding blacklist zones exclude adobedtm.com
+	set service dns forwarding blacklist zones exclude coremetrics.com
+	set service dns forwarding blacklist zones exclude doubleclick.net
+	set service dns forwarding blacklist zones source malc0de.com description 'List of zones serving malicious executables observed by malc0de.com/database/'
+	set service dns forwarding blacklist zones source malc0de.com prefix zone
+	set service dns forwarding blacklist zones source malc0de.com url 'http://malc0de.com/bl/ZONES'
+	set system task-scheduler task update_blacklists executable path /config/scripts/update-blacklists-dnsmasq.pl
+	set system task-scheduler task update_blacklists interval 6h
 
 	echo "Committing configuration..."
-	commit || ERROR=1
+	commit
 
 	echo "Saving configuration..."
-	save || ERROR=1
+	save
 
 	echo "Ending configuration session..."
-	end || ERROR=1
+	end
 
 	return ${ERROR}
 }
 
 # This is where we run the script using the above functions
-trap atexit exit ${?}
 
 if is_version
 then
-	echo "${ME}Installing ADBLOCK and Blacklist blocking dnsmasq support..."
-	if install_adblock_support
+	echo "${ME}Installing BLACKLIST and Blacklist blocking dnsmasq support..."
+	if install_blacklist_support
 	then
-		echo "${ME}ADBLOCK and Blacklist blocking dnsmasq installation succeeded!"
+		echo "${ME}ADBlock and Blacklist blocking dnsmasq installation succeeded!"
+		echo "Updating dnsmasq configuration..."
+		/config/scripts/update-blacklists-dnsmasq.pl --showstats
 	else
-		echo "${ME}ADBLOCK and Blacklist blocking dnsmasq installation failed!"
+		echo "${ME}ADBlock and Blacklist blocking dnsmasq installation failed!"
 	fi
 else
 	echo "${ME}Edgemax ${VER} is not supported, upgrade!"
diff --git a/AdBlock/payload/remove_adblock b/AdBlock/payload/remove_adblock
--- a/AdBlock/payload/remove_adblock
+++ b/AdBlock/payload/remove_adblock
@@ -6,7 +6,7 @@
 #
 # This program is distributed in the hope that it will be useful, but
 # WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the GNU
 # General Public License for more details.
 #
 # A copy of the GNU General Public License is available as
@@ -20,16 +20,17 @@
 # Date: September 2015
 #
 # **** End License ****
-# Remove dnsmasq ADBLOCK and blacklist blocking from an EdgeMax router
+# Remove dnsmasq Blacklist and blacklist blocking from an EdgeMax router
 # Use at your own risk
 #
+set -o errtrace
 
-VERSION="v2.1"
+VERSION="v2.4"
 
 # Uncomment for debugging or syntax checking
 # set -x
 # Syntax check - uncomment for non execution dry run:
-# set -n
+# set -nv
 
 # Make sure script runs as root
 if [[ ${EUID} != 0 ]]
@@ -44,16 +45,15 @@ OPRUN=/opt/vyatta/bin/vyatta-op-cmd-wrapper
 CFGRUN=/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper
 API=/bin/cli-shell-api
 shopt -s expand_aliases
-
-alias begin='${CFGRUN} begin'
-alias commit='${CFGRUN} commit'
-alias copy='${CFGRUN} copy'
-alias delete='${CFGRUN} delete'
-alias discard='${CFGRUN} discard'
-alias end='${CFGRUN} end'
-alias save='${CFGRUN} save'
-alias set='${CFGRUN} set'
-alias version='${OPRUN} show version'
+alias begin="${CFGRUN} begin"
+alias commit="${CFGRUN} commit"
+alias copy="${CFGRUN} copy"
+alias delete="${CFGRUN} delete"
+alias discard="${CFGRUN} discard"
+alias end="${CFGRUN} end"
+alias save="${CFGRUN} save"
+alias set="${CFGRUN} set"
+alias version="${OPRUN} show version"
 
 SHOWVER=$(version | sed 's/$/;/g')
 BUILD=$(echo ${SHOWVER} | awk 'BEGIN {RS=";"} /Build ID:/ {print $3}')
@@ -64,53 +64,103 @@ ERROR=0
 # Make sure we clean up session on deliberate and accidental exits
 atexit ()
 {
+	trap "" ERR
 	end
+	trap - ERR
 }
+trap atexit exit ${?}
+
+# Enable error tracing functionality
+##################################################################
+# Copyright (c): Hilario J. Montoliu <hmontoliu@gmail.com>
+# This program is free software; you can redistribute it and/or modify it
+# under the terms of the GNU General Public License as published by the
+# Free Software Foundation; either version 2 of the License, or (at your
+# option) any later version.  See http://www.gnu.org/copyleft/gpl.html for
+# the full text of the license.
+##################################################################
+report_error ()
+{
+	trap "" ERR
+	local ERR=$1 # error status
+	local LINE=$2 # LINENO
+	local FUNCTLINE=$3
+	local CMD="$4"
+	local STACK="$5"
+	echo "==================================================="
+	echo "Error: '${CMD}' exited with status: ${ERR} at line ${LINE}"
+
+	if [ "${STACK}" != "::" ]; then
+		echo -n "	... Error at ${STACK} "
+		[ -z ${FUNCTLINE:=0} ] && echo -n "called at line ${FUNCTLINE}"
+	else
+		echo -n "	... internal debug info from function ${FUNCNAME} (line ${FUNCTLINE})"
+	fi
+	echo
+	echo "==================================================="
+	trap - ERR
+}
+
+trap 'report_error $? ${LINENO} ${BASH_LINENO} "${BASH_COMMAND}" $(printf "::%s" ${FUNCNAME[@]})'  ERR
+# End of error tracing functions
+##################################################################
 
 # Install adblock and bogon support
 delete_adblock_support ()
 {
-	SCRIPTS="/config/scripts"
-	ADBLOCK="update-blacklists-dnsmasq.pl"
+	CONFIG="/config/scripts"
+	SCRIPT="update-blacklists-dnsmasq.pl"
+	DNSMASQ="/etc/dnsmasq.d"
+	CNFFILE="blacklist.conf"
 	CFGDIR="/opt/vyatta/share/vyatta-cfg/templates/service/dns/forwarding"
 	BLKLIST="blacklist"
-	ERROR=0
 
-	echo "Removing ${ADBLOCK} from ${SCRIPTS}/"
-	rm -f "${SCRIPTS}/${ADBLOCK}" || ERROR=1
+	for i in fqdn zone
+	do
+		if [[ -f ${DNSMASQ}/${i}.${CNFFILE} ]]
+		then
+			echo "Removing ${DNSMASQ}/${i}.${CNFFILE}"
+			rm ${DNSMASQ}/${i}.${CNFFILE}
+		fi
+	done
+
+	echo "Removing ${SCRIPT} from ${CONFIG}/"
+	rm -f "${CONFIG}/${SCRIPT}"
 
 	echo "Opening EdgeMax configuration session..."
-	begin || ERROR=1
+	begin
 
-	echo "Removing ADBLOCK blacklist and task scheduler entry for ${ADBLOCK}..."
-	delete service dns forwarding blacklist || ERROR=1
-	delete system task-scheduler task update_blacklists  || ERROR=1
+	echo "Removing Blacklist and task scheduler task for ${SCRIPT}..."
+	delete service dns forwarding blacklist
+	delete system task-scheduler task update_blacklists
 
 	echo "Committing configuration..."
-	commit || ERROR=1
+	commit
 
 	echo "Saving configuration..."
-	save || ERROR=1
+	save
 
 	echo "Ending configuration session..."
-	end || ERROR=1
+	end
 
-	echo "Removing blacklist configuration templates for ${ADBLOCK}..."
-	rm -rf "${CFGDIR}/${BLKLIST}/"
+	echo "Removing blacklist configuration templates for ${SCRIPT}..."
+	[[ -f "${CFGDIR}/${BLKLIST}/" ]] && rm -rf "${CFGDIR}/${BLKLIST}/"
+
+	service dnsmasq restart
+
 	return ${ERROR}
 }
 
 # This is where we run the script using the above functions
-trap atexit exit ${?}
 
-if /opt/vyatta/bin/yesno -n 'Do you want to completely remove ADBLOCK? [y/N]: '
+if /opt/vyatta/bin/yesno -n 'Do you want to completely remove Blacklist? [y/N]: '
 then
 	if delete_adblock_support
 	then
-		echo 'ADBLOCK has been completely removed.'
+		echo 'Blacklist has been completely removed.'
 		exit 0
 	else
-		echo 'There were problems removing ADBLOCK'
+		echo 'There were problems removing Blacklist'
 		exit 1
 	fi
 fi
